apiVersion: v1
kind: Service
metadata:
  name: gui-service
  namespace: test-installation
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
