image: docker:latest
services:
  - docker:dind

include:
  - local: .gitlab-ci/tests/api-tests.yaml
  - local: .gitlab-ci/tests/e2e-tests.yaml

  - local: .gitlab-ci/deploy/deploy-test-installation.yaml
  - local: .gitlab-ci/deploy/publish-images.yaml

variables:
  DEPLOY_TEST_INSTALLATION:
    value: "false"
    description: "Build test installation"
    options:
      - "true"
      - "false"
  RUN_E2E_TESTS:
    value: "false"
    description: "Run E2E tests"
    options:
      - "true"
      - "false"
  RUN_API_TESTS:
    value: "false"
    description: "Run API tests"
    options:
      - "true"
      - "false"

  GCP_PROJECT_ID: "project-5c8acae4-cb3c-44bb-8a5"
  GCP_REGION: "europe-central2"
  GCP_CLUSTER_NAME: "dawid-cluster"
  GUI_LOAD_BALANCER_IP: "34.118.119.76"
  GCP_WIF_PROVIDER: "projects/704516073438/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider"
  GCP_SERVICE_ACCOUNT_EMAIL: "gitlab-ci@project-5c8acae4-cb3c-44bb-8a5.iam.gserviceaccount.com"

stages:
  - build
  - tests
