deploy-test-installation:
  image: google/cloud-sdk:alpine
  stage: build
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - . .gitlab-ci/deploy/google-cloud-setup.sh
  script:
    - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - gcloud container clusters get-credentials "${GCP_CLUSTER_NAME}" --zone "${GCP_ZONE}" --project "${GCP_PROJECT_ID}"
    - kubectl delete namespace test-installation --ignore-not-found=true
    - kubectl create namespace test-installation
    - helm upgrade --install api app/api/deployment -n test-installation --set image=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/api:latest
    - helm upgrade --install gui app/gui/deployment -n test-installation --set image=${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/gui:latest --set loadBalancerIP=${GUI_LOAD_BALANCER_IP}
  rules:
    - if: $DEPLOY_TEST_INSTALLATION == "true"
  needs:
    - job: publish-images
