deploy-test-installation:
  image: google/cloud-sdk:alpine
  stage: build
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - . .gitlab-ci/deploy/google-cloud-setup.sh
  script:
    - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - HELMFILE_VERSION="0.169.0"
    - curl -fsSL "https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz" -o /tmp/helmfile.tar.gz
    - tar -xzf /tmp/helmfile.tar.gz -C /tmp helmfile
    - install /tmp/helmfile /usr/local/bin/helmfile
    - echo "$(gcloud auth print-access-token)" | helm registry login -u oauth2accesstoken --password-stdin https://${GCP_REGION}-docker.pkg.dev
    - gcloud container clusters get-credentials "${GCP_CLUSTER_NAME}" --zone "${GCP_ZONE}" --project "${GCP_PROJECT_ID}"
    - kubectl create namespace test-installation --dry-run=client -o yaml | kubectl apply -f -
    - export CHART_VERSION=0.1.${CI_PIPELINE_IID}
    - helmfile -f deployment/helmfile/helmfile.yaml sync
  rules:
    - if: $DEPLOY_TEST_INSTALLATION == "true"
  needs:
    - job: publish-images
