publish-images:
  stage: build
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - . .gitlab-ci/deploy/google-cloud-setup.sh
    - docker build -t ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/api:latest -f app/api/Dockerfile app/api
    - docker push ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/api:latest
    - docker build -t ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/gui:latest -f app/gui/Dockerfile app/gui
    - docker push ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/apps/gui:latest
  rules:
    - if: >-
        $DEPLOY_TEST_INSTALLATION == "true"
