apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: test-installation
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
