apiVersion: v1
kind: Service
metadata:
  name: gui-service
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  selector:
    app: gui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
