apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
